name: Ipgeobase

on:
  push:
    branches:
      [ "main" ]

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
    - name: Run the default task
      run: bundle exec rake
    
